### ISSUE TITLE
IE Compatibility?

### ISSUE THREAD

**Issue by tim-lukacik** [ahmedrad/sliiide#1]
I see quite a few issues when viewing in IE11 on my machine. The slid elements do not have their visibility unhidden and are not in the correct position. Also, on your demo site content from the bottom slide is appearing on the main page before clicking anything (the tweet button), the main text not vertically centered, and the menu hamburger is distorted. 

In Chrome I found that if the content of the page is > the view height the bottom slider does not slide up all the way.

I tested this on a single page with a sliiide from each direction (similar to the demo) with horizontal slides 100vw, and vertical slides 100vh.

Slick library. Thank you for sharing it.

**Comment by evadsetniram** [comment]
In Chrome Version 45.0.2454.85 and Firefox 40.0.3, everything is working just fine but  on my guest windows IE 10, slide menu is not showing, I thinks some sort of CSS problem, cause the element is there but not visible. I attach the actual view of my IE 10 running on virtualbox
![ie-10](https://cloud.githubusercontent.com/assets/5397321/9924770/0f06d2e4-5d35-11e5-8bcb-d2a303e70e24.png)
.

**Comment by ahmedrad** [comment]
For IE, I don't own a windows laptop but I'll try my best to test it out and fix some stuff so thanks for reporting the issues!

For the twitter button, The code of the tweet button changed and twitter is now adding an in-style property for the visibility to be 'visible'. That's why it's appearing out of nowhere on my demo site on all browsers, my demo site is kind of a special case because it has 4 hidden menus in there that I keep switching between every time the respective blue button is clicked. I'm gonna try to hide the menus not in use, I don't think that has an affect on the plugin usage though, unless you're also using twitter's button lol.

**Comment by ahmedrad** [comment]
Hey @nightcoder824 I noticed the strange behaviour that IE was doing and updated the plugin to better support it. Give it a shot and let me know how it goes, IE9 and up should be working fine.

Note: Please ignore the layout problems of the demo page on IE, I built it all using mostly flexbox and it's not meant to support all browsers.

@tim-lukacik gonna work on the bottom sliiider problem that you're experiencing next, I'll keep you posted.

**Comment by ahmedrad** [comment]
Ok I've done some work to make the plugin work for IE 10,11 and Edge .. I don't see any big problems for IE 9 but I'll go on the safer side and mention that it's not supported. I'll close this issue for now as I have tested the newer IE versions mentioned above, I've also adjusted the positioning for the bottom slider in case the page is longer than viewport height. So both these issues should be resolved @nightcoder824 @tim-lukacik 

P.S. the demo page is still gonna look like crap in IE < 12 because it's using a lot of flex box .. the sliiider functionality should be working fine though.
