### ISSUE TITLE
Html Overflow-X: Hidden Issue

### ISSUE THREAD

**Issue by xstortionist** [ahmedrad/sliiide#9]
Noticed when toggling a class that there is a flicker for overflow-x: hidden on the HTML tag. I added overflow-x hidden as an attribute to my stylesheet to correct the issue. Not sure if this is the way to go but thought I'd report the issue.

Also, if I remove the toggle class jquery on click function that I created, the horizontal scroll bar flicker no longer appears.

Hope this helps.

**Comment by ahmedrad** [comment]
thanks @xstortionist, 
The overflow-x hidden property is added to the html tag so that in case of mobile the user can't pan around the webpage since everything has been shifted using translate-x by the width of the slider .. if the user is able to pan it ruins the experience. I originally tried to apply it to the body tag only but some browsers on mobile ignore it unless it's on the html tag too. I'm not sure what flicker you're experiencing because I haven't noticed anything on my test pages. Can you link me to your page if you have it hosted somewhere? or a fiddle or a pen would be really helpful. It's hard to troubleshoot what I can't see!

Cheers,

**Comment by xstortionist** [comment]
@ahmedrad I'll try and get something up for you on my server today so u can see.

**Comment by xstortionist** [comment]
here check it out:

http://2bitwebsolutions.com/sliiide/

**Comment by ahmedrad** [comment]
@xstortionist I don't really see you using sliiide in the above link, there's another plugin there called mmenu. Not sure if you confused the two or I'm looking at the wrong thing.

Cheers,

**Comment by ahmedrad** [comment]
hi @xstortionist I'm gonna close this issue for now as I still can't see sliiide used on the example website you gave. Feel free to re-open it with more info if you need to!

Cheers,
